export const ErrorCodes = {
    INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    OTP_EXPIRED: 'OTP_EXPIRED',
    PHONE_NUMBER_NOT_FOUND: 'PHONE_NUMBER_NOT_FOUND',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    DB_ERROR: 'DB_ERROR',
    INVALID_OTP: 'INVALID_OTP',
    USER_EXISTS: 'USER_EXISTS'
};