export const ErrorCodes = {
    INVALID_REQUEST: 'INVALID_REQUEST',
    INVALID_PHONENUMBER: 'INVALID_PHONENUMBER',
    PARTNER_ACCOUNT_DOESNOT_EXIST: 'PARTNER_ACCOUNT_DOESNOT_EXIST',
    NOT_ACCEPTED_PRIVACY_POLICY: 'NOT_ACCEPTED_PRIVACY_POLICY',
    NOT_ACCEPTED_TERMS_AND_CONDITIONS: 'NOT_ACCEPTED_TERMS_AND_CONDITIONS',
    PHONE_NUMBER_REQUIRED: 'PHONE_NUMBER_REQUIRED',
};